section_list = []
section_list.append("FILE SYSTEM INFORMATION\n--------------------------------------------\nFile System Type: ")
section_list.append("\nOEM Name: ")
section_list.append("Volume ID: ")
section_list.append("Volume Label (Boot Sector): ")
section_list.append("\nFile System Type Label: ")
section_list.append("\nFile System Layout (in sectors) ")
section_list.append("Total Range: ")
section_list.append("Total Range in Image: ")
section_list.append("* Reserved:  ")
section_list.append("** Boot Sector: ")
section_list.append("* FAT 0: ")
section_list.append("* FAT 1: ")
section_list.append("Data Area: ")
section_list.append("** Root Directory: ")
section_list.append("Cluster Area: ")
section_list.append("Non-clustered: ")
section_list.append("\nCONTENT INFORMATION\n--------------------------------------------\nSector Size: ")
section_list.append("Cluster Size: ")
section_list.append("Total Cluster Range: ")